<?php
namespace App\Mod\Article\Domain;

use App\Domain\BaseService;
use App\Mod\Article\Domain\Models\Article;
use Symfony\Component\HttpFoundation\Request;

/**
 * @property Article $model
 */
class ArticleService extends BaseService
{
    public function __construct(Article $model)
    {
        parent::__construct($model);
    }

    public function findList(Request $request, ?int $limit = null): array
    {
        if (!$limit) {
            $limit = config('article.list.limit');
        }
        return parent::findList($request, $limit); // TODO: Change the autogenerated stub
    }
}
