<?php
namespace App\Mod\News\Tests\Unit;

use App\Mod\News\Domain\NewsService;
use App\Mod\News\Domain\Models\News;
use Symfony\Component\HttpFoundation\Request;
use Tests\Unit\AbstractUnitTest;

class NewsDomainTest extends AbstractUnitTest
{
    /** @var NewsService $service */
    protected $service;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = \app()->make(NewsService::class);
    }

    public function test_list()
    {
        // データ7件作成
        News::factory(7)->create();

        // 1ページ目テスト
        $request = new Request();
        $request->query->add([
            'current' => 1,
            'limit' => 5
        ]);
        $result = $this->service->findList($request);
        $this->assertEquals($result['total'], 7);
        $this->assertEquals(count($result['data']), 5);

        // 2ページ目テスト
        $request = new Request();
        $request->query->add([
            'current' => 2,
            'limit' => 5
        ]);
        $result = $this->service->findList($request);
        $this->assertEquals($result['total'], 7);
        $this->assertEquals(count($result['data']), 2);
    }

    public function test_detail()
    {
        // データ作成
        $createPost = News::factory()->create();
        // データ取得
        $getPost = $this->service->findDetail($createPost->id);
        // 同じデータかテスト
        $this->assertEquals($createPost->title, $getPost->title);
    }

    public function test_save()
    {
        // データ作成テスト
        $inputData = News::factory()->make()->toArray();
        $request = new Request();
        $request->request->add($inputData);
        $result = $this->service->save($request);
        $post = News::find($result->id);
        $this->assertEquals($inputData['title'], $post->title);

        // データ更新テスト
        $inputData['title'] .= ' edit';
        $request->request->add($inputData);
        $this->service->save($request, $result->id);
        $post = News::find($result->id);
        $this->assertEquals($inputData['title'], $post->title);
    }

    public function test_delete()
    {
        $createPost = News::factory()->create();
        $this->assertEquals(News::count(), 1);

        $this->service->delete($createPost->id);
        $this->assertEquals(News::count(), 0);
    }
}
