<?php
namespace App\Mod\News\Domain;

use App\Domain\BaseService;
use Symfony\Component\HttpFoundation\Request;
use App\Mod\News\Domain\Models\News;

class NewsService extends BaseService
{

    public function __construct(News $model)
    {
        parent::__construct($model);
    }

    public function findList(Request $request, ?int $limit = null): array
    {
        if (!$limit) {
            $limit = config('news.list.limit');
        }
        return parent::findList($request, $limit); // TODO: Change the autogenerated stub
    }

}
