name: Deploy to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

          sudo su -

          cd /root/abi-cms/
          git pull

          podman exec cms_frontend npm install || exit 1

          cd ./backend/src/

          podman exec cms_backend php artisan migrate --force

          # コンテナの状態確認
          echo "Checking container status..."
          podman ps -a | grep website

          # 既存のコンテナを停止・削除
          echo "Cleaning up existing container..."
          podman stop website || true
          podman rm website || true

          # コンテナの再作成（エントリーポイントとコマンドを明示的に指定）
          echo "Creating new container with adjusted memory limits..."
          podman run -d \
            --name website \
            --memory="4g" \
            --memory-swap="6g" \
            --entrypoint "/bin/sh" \
            localhost/abi-cms_website:latest \
            -c "cd /app && npm install && npm run dev"

          # コンテナの状態確認
          echo "Verifying container status..."
          podman ps -a | grep website

          # コンテナログの確認とエラー検出
          echo "Checking container logs..."
          sleep 5  # ログ出力を待機

          if ! podman logs website; then
            echo "Failed to get container logs"
            exit 1
          fi

          # コンテナの実行状態を確認
          CONTAINER_STATUS=$(podman inspect website --format '{{.State.Status}}')
          echo "Container status: $CONTAINER_STATUS"

          if [ "$CONTAINER_STATUS" != "running" ]; then
            echo "Container failed to start properly"
            podman logs website
            exit 1
          fi

          # コンテナ内のプロセス確認
          echo "Checking container processes..."
          if ! podman top website; then
            echo "Failed to check container processes"
            podman logs website
            exit 1
          fi

          echo "Starting build process..."

          # NPMプロセスの実行確認
          echo "Installing dependencies..."
          if ! podman exec website /bin/sh -c 'cd /app && NODE_OPTIONS="--max_old_space_size=3072" npm install'; then
            echo "Failed to install dependencies:"
            podman logs website
            exit 1
          fi

          echo "Building application..."
          if ! podman exec website /bin/sh -c 'cd /app && NODE_OPTIONS="--max_old_space_size=3072" npm run build'; then
            echo "Failed to build application:"
            podman logs website
            exit 1
          fi

          echo "Restarting PM2..."
          if ! podman exec website /bin/sh -c 'cd /app && pm2 restart all'; then
            echo "Failed to restart PM2:"
            podman logs website
            exit 1
          fi

          echo "Deployment completed successfully"

          exit

          EOF
