name: Deploy to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

          sudo su -

          cd /root/abi-cms/
          git pull

          podman exec cms_frontend npm install || exit 1

          cd ./backend/src/

          podman exec cms_backend php artisan migrate --force

          # コンテナの起動確認と再試行のロジックを追加
          if ! podman ps | grep -q website; then
          echo "Starting website container..."
          podman start website

          # コンテナの起動を待機
          echo "Waiting for container to be ready..."
          for i in {1..30}; do
          if podman ps | grep -q website; then
          echo "Container is running"
          break
          fi
          echo "Waiting... ($i/30)"
          sleep 2
          done
          fi

          # コンテナの状態を再確認
          if ! podman ps | grep -q website; then
          echo "Failed to start container"
          exit 1
          fi

          # コンテナが確実に起動している状態でコマンドを実行
          podman exec website bash -c "cd /app && npm install && npm run build && pm2 restart all"
          exit

          EOF
