name: Deploy to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

          sudo su -

          cd /root/abi-cms/
          git pull

          podman exec cms_frontend npm install || exit 1

          cd ./backend/src/

          podman exec cms_backend php artisan migrate --force

          # コンテナの状態確認
          echo "Checking container status and memory limits..."
          podman ps -a | grep website
          podman inspect website | grep -i memory

          # websiteコンテナの再作成（必要な場合）
          if ! podman ps | grep -q website; then
            echo "Recreating website container with adjusted memory limits..."
            podman stop website || true
            podman rm website || true

            # コンテナの再作成（メモリ制限付き）
            podman run -d \
              --name website \
              --memory="4g" \
              --memory-swap="6g" \
              localhost/abi-cms_website:latest
          else
            echo "Starting existing website container..."
            podman start website
          fi

          # コンテナの起動を待機
          echo "Waiting for container to be ready..."
          for i in {1..30}; do
            if podman ps | grep -q website; then
              echo "Container is running"
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done

          # コンテナの状態を再確認
          if ! podman ps | grep -q website; then
            echo "Failed to start container"
            exit 1
          fi

          # 段階的なビルドプロセスの実行
          echo "Installing dependencies..."
          podman exec website bash -c 'cd /app && NODE_OPTIONS="--max_old_space_size=3072" npm install'

          if [ $? -ne 0 ]; then
            echo "Failed to install dependencies"
            exit 1
          fi

          echo "Building application..."
          podman exec website bash -c 'cd /app && NODE_OPTIONS="--max_old_space_size=3072" npm run build'

          if [ $? -ne 0 ]; then
            echo "Failed to build application"
            exit 1
          fi

          echo "Restarting PM2..."
          podman exec website bash -c 'cd /app && pm2 restart all'

          if [ $? -ne 0 ]; then
            echo "Failed to restart PM2"
            exit 1
          fi

          echo "Deployment completed successfully"

          exit

          EOF
