name: Deploy to Server

on:
    push:
        branches: [ "main"]

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout Code
          uses: actions/checkout@v3
    
        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Add known hosts
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

        - name: Deploy to Server
          run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

            sudo su -
                
            cd /root/abi-cms/
            git pull
            
            docker exec cms_frontend npm install || exit 1
            
            # ポート3000を使用しているプロセスを検索して終了
            docker exec website sh -c "lsof -i:3000 -t | xargs kill -9" || true
            # 少し待機
            sleep 2
            # コンテナを再起動
            docker restart website
  
            # コンテナが完全に起動するまで待機
            sleep 10
            
            docker exec website node -v
            docker exec website npm -v
            
            docker exec website sh -c "lsof -i:3000"
            
            docker exec website npm install
            
            sleep 10
  
            # Next.jsアプリケーションを再ビルド
            docker exec website npm run build
            docker exec -d website sh -c "PORT=3001 npm run start"           
            
            cd ./backend/src/
          
            docker exec -it cms_backend bash

            php artisan migrate --force
            
            exit
            
            EOF
