name: Deploy to Server

on:
    push:
        branches: [ "main"]

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout Code
          uses: actions/checkout@v3
    
        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Add known hosts
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

        - name: Deploy to Server
          run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

            sudo su -
                
            cd /root/abi-cms/
            git pull
            
            docker exec cms_frontend npm install || exit 1
            
            # websiteコンテナを再起動
            docker restart website
            
            # コンテナが完全に起動するまで少し待機
            sleep 10
            
            # キャッシュのクリアと依存関係の再インストール
            docker exec website npm cache clean --force
            
            # node_modulesを削除 (コンテナ再起動後なので削除できるはず)
            docker exec website rm -rf node_modules || true
            
            # package-lockの削除と再インストール
            docker exec website rm -f package-lock.json
            docker exec website npm install
            docker exec website npm install autoprefixer@10.4.21 --save-dev
            
            # Next.jsアプリケーションを再ビルド
            docker exec website npm run build
            
            # Next.jsアプリケーションを再起動（必要に応じて）
            docker exec website npm run start

            cd ./backend/src/
          
            docker exec -it cms_backend bash

            php artisan migrate --force
            
            exit
            
            EOF
