name: Deploy to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

          sudo su -
              
          cd /root/abi-cms/
          git pull

          docker exec cms_frontend npm install || exit 1

          # websiteコンテナを完全に再ビルド
          docker-compose build --no-cache website
          docker-compose up -d website
          # docker image prune -a -f
          # sleep 10

          # コンテナを再起動
          # docker-compose restart
          # websiteのみ
          # docker restart website
          # reverse-proxyのみ
          # docker-compose restart reverse-proxy
          # sleep 10

          #コンテナの状態確認
          docker ps
          docker image ls
          # docker ps | grep website
          # docker logs reverse-proxy
          docker exec website node -v
          docker exec website npm -v
          docker logs website
          # docker exec website ps aux | grep node

          # nextjs用のpackageを再インストール
          # docker exec website npm cache clean --force
          # sleep 10
          # docker exec website rm -rf node_modules
          # sleep 5
          # docker exec website rm -f package-lock.json
          # sleep 2
          # docker exec website npm install
          # sleep 10

          # Nginxのログ確認
          # docker exec reverse-proxy ls -la /var/log/nginx/
          # docker exec reverse-proxy cat /var/log/nginx/error.log

          cd ./backend/src/

          docker exec -it cms_backend bash

          php artisan migrate --force

          exit

          EOF
