- name: Deploy to Server
  run: |
    ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

    sudo su -
    cd /root/abi-cms/
    git pull

    # フロントエンドの依存関係インストール
    docker exec cms_frontend npm install || exit 1

    # バックエンドのマイグレーション実行
    docker exec cms_backend php artisan migrate --force || exit 1

    # コンテナを再起動
    docker restart cms_backend
    docker restart cms_frontend

    # コンテナの状態確認
    docker ps

    exit
    EOF
